
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: bill-organizer_development
test:
  <<: *default
  database: bill-organizer_test

#
production:
  <<: *default
  database: bill-organizer_production
  username: bill-organizer
  password: <%= ENV['BILL-ORGANIZER_DATABASE_PASSWORD'] %>
