source 'https://rubygems.org'
gem 'rails', '4.2.1'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'

gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

gem 'bootstrap-sass'
gem 'backbone-on-rails'
gem 'jquery-ui-rails'

 gem 'bcrypt', '~> 3.1.7'
gem 'ruby', '2.1.2'
group :development, :test do
  gem 'byebug'

  gem 'web-console', '~> 2.0'

  gem 'spring'
  gem 'annotate'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'pry-rails'
end
